# Generated by Django 5.2.7 on 2026-01-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articolo_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='visualizzazione',
            new_name='visualizzazioni',
        ),
    ]
